# Generated by Django 5.1.4 on 2024-12-10 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_fullName', models.CharField(max_length=100)),
                ('agent_email', models.CharField(max_length=100)),
                ('total_ticket', models.IntegerField()),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='open', max_length=100)),
                ('issue', models.TextField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('close', models.DateField(default=None, null=True)),
                ('user_fullName', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=150)),
                ('user_contactNumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAssigned',
            fields=[
                ('assigned_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_number', models.IntegerField(default=0)),
                ('assigned_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_api.ticket')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_api.agent')),
            ],
        ),
    ]
