# Generated by Django 5.1.4 on 2024-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='total_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
